const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const palettes={spectrum:['#3326a8','#126de0','#00c5cf','#56dc75','#f5e94b','#ff8a2b','#e9364f'],ocean:['#152a5b','#175d8d','#2ca6a4','#a7d46f','#f2d15c'],magma:['#251255','#7b1f70','#d33f5f','#f98e52','#f9e784'],mono:['#13283b','#36566e','#7691a3','#c3ced4']};
let demFile=null,grid=null,starts=[],svgBlob=null,svgUrl=null;
const canvas=$('#terrainCanvas'),ctx=canvas.getContext('2d');
function setStatus(text,error=false){$('#status').textContent=text;$('#status').classList.toggle('error',error)}
function paletteColor(t){const p=palettes[$('#palette').value],v=Math.max(0,Math.min(.9999,t))*(p.length-1),i=Math.floor(v),f=v-i;const a=p[i].match(/\w\w/g).map(x=>parseInt(x,16)),b=p[i+1].match(/\w\w/g).map(x=>parseInt(x,16));return `rgb(${a.map((x,k)=>Math.round(x+(b[k]-x)*f)).join(',')})`}
function updateStrip(){$('#paletteStrip').style.background=`linear-gradient(90deg,${palettes[$('#palette').value].join(',')})`;if(grid)drawTerrain()}
function drawTerrain(){if(!grid)return;const w=canvas.width,h=canvas.height,gh=grid.length,gw=grid[0].length,img=ctx.createImageData(w,h);for(let y=0;y<h;y++){const row=grid[Math.floor(y/h*gh)];for(let x=0;x<w;x++){const z=row[Math.floor(x/w*gw)],rgb=paletteColor((z+1.8)/3.6).match(/\d+/g).map(Number),o=(y*w+x)*4;img.data[o]=rgb[0];img.data[o+1]=rgb[1];img.data[o+2]=rgb[2];img.data[o+3]=210}}ctx.putImageData(img,0,0);ctx.strokeStyle='rgba(255,255,255,.22)';ctx.lineWidth=1;for(let i=0;i<=16;i++){ctx.beginPath();ctx.moveTo(i*w/16,0);ctx.lineTo(i*w/16,h);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*h/16);ctx.lineTo(w,i*h/16);ctx.stroke()}starts.forEach((p,i)=>{const x=p[0]*w,y=p[1]*h;ctx.beginPath();ctx.arc(x,y,12,0,Math.PI*2);ctx.fillStyle='#f8f5ee';ctx.fill();ctx.lineWidth=4;ctx.strokeStyle='#17324d';ctx.stroke();ctx.fillStyle='#17324d';ctx.font='bold 13px ui-monospace';ctx.fillText(String(i+1),x+18,y+5)});$('#pointCount').textContent=`${starts.length} start point${starts.length===1?'':'s'}`}
async function analyze(file){demFile=file;$('#fileName').textContent=file.name;$('#title').value=file.name.replace(/\.[^.]+$/,'').replace(/[-_]+/g,' ').toUpperCase();$('#loading').classList.add('show');$('#terrainShell').classList.remove('empty');setStatus('Reading and normalizing the DEM…');const form=new FormData();form.append('file',file);form.append('smoothing',$('#smoothing').value);form.append('resolution','96');try{const r=await fetch('/api/preview',{method:'POST',body:form}),data=await r.json();if(!r.ok)throw new Error(data.error);grid=data.grid;starts=[];drawTerrain();$('#generate').disabled=false;setStatus('DEM ready. Click the terrain to place a start point.')}catch(e){grid=null;$('#terrainShell').classList.add('empty');$('#generate').disabled=true;setStatus(e.message,true)}finally{$('#loading').classList.remove('show')}}
$('#demFile').addEventListener('change',e=>e.target.files[0]&&analyze(e.target.files[0]));
const dz=$('#dropzone');['dragenter','dragover'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>e.dataTransfer.files[0]&&analyze(e.dataTransfer.files[0]));
canvas.addEventListener('click',e=>{if(!grid)return;const r=canvas.getBoundingClientRect();starts.push([(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height]);drawTerrain()});
$('#undoStart').onclick=()=>{starts.pop();drawTerrain()};$('#clearStarts').onclick=()=>{starts=[];drawTerrain()};
$('#steps').oninput=e=>$('#stepsOut').value=e.target.value;$('#palette').onchange=updateStrip;updateStrip();
$('#smoothing').addEventListener('change',()=>demFile&&analyze(demFile));
function config(){return{title:$('#title').value||'UNTITLED DEM',steps:+$('#steps').value,start_points:starts.length?starts:[[.5,.5]],optimizers:$$('#optimizers input:checked').map(x=>x.value),palette:$('#palette').value,smoothing:+$('#smoothing').value,grid_lines:+$('#lines').value,vertical_scale:+$('#heightScale').value,fill_opacity:+$('#fillOpacity').value,auto_fit:true,surface_top:90,surface_bottom:1185}}
$('#generate').onclick=async()=>{if(!demFile)return;if(!$$('#optimizers input:checked').length){setStatus('Select at least one optimizer.',true);return}const button=$('#generate');button.disabled=true;button.querySelector('span').textContent='Generating…';setStatus('Projecting terrain and tracing optimizer paths…');const form=new FormData();form.append('file',demFile);form.append('smoothing',$('#smoothing').value);form.append('resolution','96');form.append('config',JSON.stringify(config()));try{const r=await fetch('/api/render',{method:'POST',body:form});if(!r.ok){const d=await r.json();throw new Error(d.error)}svgBlob=await r.blob();if(svgUrl)URL.revokeObjectURL(svgUrl);svgUrl=URL.createObjectURL(svgBlob);$('#artPreview').src=svgUrl;$('#artShell').classList.remove('empty');$('#downloadSvg').disabled=$('#downloadPng').disabled=false;setStatus('Artwork generated. SVG is print-ready and fully editable.')}catch(e){setStatus(e.message,true)}finally{button.disabled=false;button.querySelector('span').textContent='Generate artwork'}};
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#downloadSvg').onclick=()=>svgBlob&&download(svgBlob,`${($('#title').value||'dem-art').toLowerCase().replace(/[^a-z0-9]+/g,'-')}.svg`);
$('#downloadPng').onclick=()=>{if(!svgUrl)return;const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=2400;c.height=3200;c.getContext('2d').drawImage(img,0,0,c.width,c.height);c.toBlob(b=>download(b,`${($('#title').value||'dem-art').toLowerCase().replace(/[^a-z0-9]+/g,'-')}.png`),'image/png')};img.src=svgUrl};
